### ISSUE TITLE
script/runner Error: Could not find or load main class quickstart.Boot

### ISSUE THREAD

**Issue by Parabellum1905y** [xitrum-framework/xitrum-new#13]
Hello !
when i've runned command:
script/runner quickstart.Boot
it returns 
Error: Could not find or load main class quickstart.Boot
after small 'fixing' runner script, it works. I've added this string :
ROOT_DIR="$ROOT_DIR/target/xitrum"
before:
cd "$ROOT_DIR"

**Comment by ngocdaothanh** [comment]
Hi. Thanks but this is not a bug.

It's because after running:
```
sbt/sbt xitrum-package
```

The directory `target/xitrum` will be created, and `script/runner` will be copied there. Then you run it from the directory `target/xitrum`, not from the project source code root directory.

`target/xitrum` is intended to be self-contained. You can copy it to other machines to run (with `script/runner`).

**Comment by ngocdaothanh** [comment]
Trivia: "Xitrum" means ["Les Schtroumpfs" or "The Smurfs"](https://en.wikipedia.org/wiki/The_Smurfs), which means "everything" or "anything". So everything you need is already inside the directory `target/xitrum`. Just copy it to other machines to run.

**Comment by Parabellum1905y** [comment]
Ok, Sorry, its my error. Thank you for the answer
